### ISSUE TITLE
Indexing errors

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/ecodata#458]
There are regular errors when indexing Sites.
java.lang.NullPointerException: Cannot get property '_id' on null object
        at au.org.ala.ecodata.SiteService.toMap(SiteService.groovy:118)
        at au.org.ala.ecodata.ElasticSearchService.indexDocType(ElasticSearchService.groovy:477)
        at au.org.ala.ecodata.ElasticSearchService.indexDocType(ElasticSearchService.groovy:512)

It appears that the findBySiteId is returning null during indexing.

**Comment by chrisala** [comment]
This is caused by biocollect#998
