### ISSUE TITLE
ConcurrentModificationException in documentation handler

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/ecodata#618]
The handler for `/documentation/index` showed a `ConcurrentModificationException` on ecodata-test today. This indicates that the LinkedHashMap has items being added and/or removed from it while it is being iterated over.

```
==> /var/log/tomcat7/ecodata.log <==
2020-10-16 14:58:31,497 WARN  [MetadataService]  No template found with name tasVegFloristicComposition
2020-10-16 14:58:31,501 WARN  [MetadataService]  No template found with name weedMappingAndMonitoring-withMap
2020-10-16 14:58:31,502 WARN  [MetadataService]  No template found with name bfOutcomesAndMonitoring
2020-10-16 14:58:31,520 WARN  [MetadataService]  No template found with name assetProtectionDetails
2020-10-16 14:58:31,521 WARN  [MetadataService]  No template found with name ecologicalBurnDetails
2020-10-16 14:58:31,652 WARN  [MetadataService]  No template found with name tasVegNvaMethod_NF
2020-10-16 14:58:31,655 WARN  [MetadataService]  No template found with name feralAnimalAbundanceScore
2020-10-16 14:58:31,658 WARN  [MetadataService]  No template found with name feralAnimalFrequencyScore
2020-10-16 14:58:31,661 WARN  [MetadataService]  No template found with name siteAssessment
2020-10-16 14:58:31,663 WARN  [MetadataService]  No template found with name siteConditionComponents
2020-10-16 14:58:31,666 WARN  [MetadataService]  No template found with name landscapeContextComponents
2020-10-16 14:58:31,669 WARN  [MetadataService]  No template found with name saStructuralDiversity
2020-10-16 14:58:31,672 WARN  [MetadataService]  No template found with name saWeedAbundanceAndThreat
2020-10-16 14:58:31,694 WARN  [MetadataService]  No template found with name summaryReportDataUpload
2020-10-16 14:58:31,697 WARN  [MetadataService]  No template found with name gaMonthlyReportData
2020-10-16 14:58:31,700 WARN  [MetadataService]  No template found with name gaQuarterlyProjectReport
2020-10-16 14:58:31,703 WARN  [MetadataService]  No template found with name gaEndOfProjectReport
2020-10-16 14:58:31,705 WARN  [MetadataService]  No template found with name gaDesktopAuditChecklist
2020-10-16 14:58:31,708 WARN  [MetadataService]  No template found with name gaTeamSupervisorAttendance
2020-10-16 14:58:31,711 WARN  [MetadataService]  No template found with name gaSiteVisitDetails
2020-10-16 14:58:31,862 WARN  [MetadataService]  No template found with name plantPropagation-withMap
2020-10-16 14:58:31,991 WARN  [MetadataService]  No template found with name CRISP-ProjectAssessment-Step2DetermineExposure
2020-10-16 14:58:31,996 WARN  [MetadataService]  No template found with name CRISP-Audit-FirstPassScan
2020-10-16 14:58:32,262 WARN  [MetadataService]  No template found with name nestBoxEstablishment
2020-10-16 14:58:33,423 ERROR [DocumentationController]  Unable to generate documentation for output: RLP Mid-term outcomes
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:752)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:750)
	at au.org.ala.ecodata.SchemaBuilder.schemaForOutput(SchemaBuilder.groovy:120)
	at au.org.ala.ecodata.DocumentationController$_index_closure3.doCall(DocumentationController.groovy:34)
	at au.org.ala.ecodata.DocumentationController.index(DocumentationController.groovy:29)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
	at org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:65)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-10-16 14:58:33,451 WARN  [MetadataService]  No template found with name apnFeralPigShooting
2020-10-16 14:58:33,673 WARN  [MetadataService]  No template found with name warrumbungleSnap
2020-10-16 14:58:33,822 WARN  [MetadataService]  No template found with name PerformanceSelfAssessment

==> /var/log/nginx/access.log <==
[REDACTED] - - [16/Oct/2020:14:58:35 +1100] "GET /documentation/index HTTP/2.0" 200 22180 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36" "-" request_time=3.582 upstream_response_time=3.580 upstream_connect_time=0.000 upstream_header_time=3.580 upstream_cache_status=-
```

**Comment by chrisala** [comment]
https://upsource.ala.org.au/ecodata/review/ECDT-CR-51
